//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeMode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int id { get; set; }
        public string name { get; set; }
        public string urlname { get; set; }
        public string uploadedby { get; set; }
        public System.DateTime uploadedon { get; set; }
        public Nullable<int> typeid { get; set; }
    
        public virtual CertType CertType { get; set; }
    }
}
